# Generated by Django 5.1.6 on 2025-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
