# Generated by Django 4.2.11 on 2025-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_bid_alter_product_status_delete_participant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
    ]
