# Generated by Django 4.2.11 on 2025-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
