# Generated by Django 4.2.11 on 2025-03-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='Product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.product'),
        ),
    ]
