# Generated by Django 5.1.6 on 2025-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
