# Generated by Django 4.2.5 on 2025-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auction_buyer_confirmed_auction_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('collectibles', 'Collectibles'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
